### PR TITLE
Feature/cart

### PR DESCRIPTION
**Pull request by andrii-pozniak**

### CODE REVIEW

**Comment by andrii-pozniak** [comment]
Feature/cart

**Comment by andrii-pozniak** [comment]
[Vitalii Mordovets](https://github.com/movitalii)

**Comment by andrii-pozniak** [comment]
Витаоий посмотри

**Comment by andrii-pozniak** [comment]
[Vitalii Mordovets](https://github.com/movitalii)

**Review by dikaryok — APPROVED** [review]

**Pull request merged**
